export const GET_RECIPE_LIST_SUCCESS = "recipe/GET_RECIPE_LIST_SUCCESS";
export const GET_RECIPE_LIST_ERROR = "recipe/GET_RECIPE_LIST_ERROR";
export const GET_RECIPE_SUCCESS = "recipe/GET_RECIPE_SUCCESS";
export const GET_RECIPE_ERROR = "recipe/GET_RECIPE_ERROR";
export const GET_INGREDIENT_LIST_SUCCESS =
  "ingredient/GET_INGREDIENT_LIST_SUCCESS";
export const GET_INGREDIENT_LIST_ERROR = "ingredient/GET_INGREDIENT_LIST_ERROR";
export const GET_INGREDIENT_SUCCESS = "ingredient/GET_INGREDIENT_SUCCESS";
export const GET_INGREDIENT_ERROR = "ingredient/GET_INGREDIENT_ERROR";
